apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
data:
  APP_ENV: "kubernetes"

---
apiVersion: v1
kind: Secret
metadata:
  name: flask-secret
type: Opaque
stringData:
  APP_MESSAGE: "Hello from Kubernetes"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 2

  selector:
    matchLabels:
      app: flask-app

  template:
    metadata:
      labels:
        app: flask-app

    spec:
      containers:
        - name: flask-app
          image: flask-app:1.0

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 5000

          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: flask-config
                  key: APP_ENV

            - name: APP_MESSAGE
              valueFrom:
                secretKeyRef:
                  name: flask-secret
                  key: APP_MESSAGE

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask-app

  minReplicas: 2
  maxReplicas: 5

  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0

    scaleDown:
      stabilizationWindowSeconds: 60

  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
